import "./globals.scss";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Contact from "@/components/contact/Contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "close end art studio.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
